---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	retrieve_docs(retrieve_docs)
	pair_facts(pair_facts)
	judge_conflict(judge_conflict)
	format_report(format_report)
	__end__([<p>__end__</p>]):::last
	__start__ --> retrieve_docs;
	judge_conflict --> format_report;
	pair_facts --> judge_conflict;
	retrieve_docs --> pair_facts;
	format_report --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
